# Generated by Django 5.0.5 on 2024-05-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHub', '0002_rename_employer_id_jobs_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
